name: Build and Deploy

on:
  push:
    branches: [development]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      # - name: Run tests (if any)
      #   run: npm test

      - name: Create env file
        run: |
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_DATABASE_DEVELOPMENT=${{ secrets.DB_DATABASE_DEVELOPMENT }}" >> .env
          echo "DB_DATABASE_TEST=${{ secrets.DB_DATABASE_TEST }}" >> .env
          echo "DB_DATABASE_PRODUCTION=${{ secrets.DB_DATABASE_PRODUCTION }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_DIALECT=${{ secrets.DB_DIALECT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop the existing process
            pm2 stop api-staging-degenmax || true

            # Clean the directory but exclude ecosystem.config.js
            find /var/www/api-staging-degenmax -mindepth 1 -not -name 'ecosystem.config.js' -delete

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".,!node_modules,.env"
          target: "/var/www/api-staging-degenmax"

      - name: Start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/api-staging-degenmax
            npm install --production
            if [ ! -f ecosystem.config.js ]; then
              echo "ecosystem.config.js not found, deployment failed"
              exit 1
            fi
            pm2 start ecosystem.config.js --env development || pm2 restart api-staging-degenmax
